package org.rrpe.intelligence.controller;

import java.util.List;
import java.util.Map;
import java.util.UUID;

import org.rrpe.intelligence.analysis.api.ClassificationRequest;
import org.rrpe.intelligence.analysis.api.RecommendationReviewRequest;
import org.rrpe.intelligence.analysis.config.BaselineLearningConfig;
import org.rrpe.intelligence.analysis.model.ChainDeadlineRecommendation;
import org.rrpe.intelligence.analysis.model.RecommendationReview;
import org.rrpe.intelligence.analysis.service.DeadlineRecommendationService;
import org.rrpe.intelligence.analysis.service.RecommendationReviewService;
import org.rrpe.intelligence.analysis.service.RecommendationService;
import org.springframework.http.ProblemDetail;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

/** Reviews plans generated by the server; never accepts edited policy bodies. */
@RestController
@RequestMapping("/api/v1/reviews")
public class RecommendationReviewController {
    private final RecommendationReviewService reviews;
    private final RecommendationService services;
    private final DeadlineRecommendationService deadlines;
    private final BaselineLearningConfig.Settings windows;

    public RecommendationReviewController(RecommendationReviewService reviews, RecommendationService services,
            DeadlineRecommendationService deadlines, BaselineLearningConfig.Settings windows) {
        this.reviews = reviews;
        this.services = services;
        this.deadlines = deadlines;
        this.windows = windows;
    }

    @GetMapping
    public List<RecommendationReview> list(@RequestParam(defaultValue = "100") int limit) {
        return reviews.findLatest(limit);
    }

    @GetMapping("/config")
    public Map<String, Long> config() {
        return Map.of("recentWindowSeconds", windows.recentWindow().toSeconds());
    }

    @GetMapping("/{recommendationId}")
    public RecommendationReview find(@PathVariable UUID recommendationId) {
        return reviews.find(recommendationId);
    }

    @PostMapping("/decisions")
    public RecommendationReview decide(@RequestBody RecommendationReviewRequest request) {
        return reviews.review(request);
    }

    /** Manual snapshots are useful for explicitly labelled synthetic dashboard demos. */
    @PostMapping("/service")
    public Submission service(@RequestBody ClassificationRequest request) {
        var plan = services.recommend(request);
        if (plan.recommendations().isEmpty()) {
            return new Submission(true, "No service policy changes are suggested.", null, plan);
        }
        return new Submission(true, "Recommendation saved for review.", reviews.submitServicePlan(plan), plan);
    }

    @PostMapping("/deadline")
    public Submission deadline(@RequestBody ChainDeadlineRecommendation.Request request) {
        var plan = deadlines.recommend(request);
        return new Submission(plan.ready(), plan.message(),
                plan.requiresApproval() ? reviews.submitDeadlinePlan(plan) : null, plan);
    }

    @ExceptionHandler(ResponseStatusException.class)
    public ProblemDetail failure(ResponseStatusException exception) {
        return ProblemDetail.forStatusAndDetail(exception.getStatusCode(), exception.getReason());
    }

    public record Submission(boolean ready, String message, RecommendationReview review, Object analysis) {
    }
}
