apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: rrpe-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:17
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres -p 5432 -U "$POSTGRES_USER"; do
                echo "waiting for postgres..."
                sleep 2
              done
          envFrom:
            - secretRef:
                name: postgres-credentials
      containers:
        - name: payment-service
          image: rrpe/payment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/paymentdb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: PAYMENT_DB
              valueFrom:
                configMapKeyRef:
                  name: rrpe-config
                  key: PAYMENT_DB
            - name: PAYMENT_SIMULATED_FAILURE_RATE
              valueFrom:
                configMapKeyRef:
                  name: rrpe-config
                  key: PAYMENT_SIMULATED_FAILURE_RATE
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            failureThreshold: 30
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 15
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: rrpe-ecommerce
spec:
  selector:
    app: payment-service
  ports:
    - port: 8083
      targetPort: 8083
