apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-deployment
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: 2002rusira/inventory-service-rpe-implementation:v1
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: rpe-config
                  key: SPRING_DATASOURCE_URL_Inventory

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rpe-secret
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rpe-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: inventory