apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: 2002rusira/notification-service-rpe-implementation:v1
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: notification