apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: 2002rusira/order-service-rpe-implementation:v1
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: rpe-config
                  key: SPRING_DATASOURCE_URL_Order

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rpe-secret
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rpe-secret
                  key: POSTGRES_PASSWORD

            - name: INVENTORY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: rpe-config
                  key: INVENTORY_SERVICE_URL

            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: rpe-config
                  key: PAYMENT_SERVICE_URL

            - name: NOTIFICATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: rpe-config
                  key: NOTIFICATION_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: order