services:
  proxy:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      PROXY_LISTEN_HOST: 0.0.0.0
      PROXY_LISTEN_PORT: 8080
      DEFAULT_DEADLINE_MILLIS: 5000
      PROXY_DETECT_INBOUND_DEADLINE: "true"
    ports:
      - "8080:8080"
